export const Icons = {
  ChevronRight: "\ue5cc",
  ChevronLeft: "\ue5cb",
  ChevronDown: "\ue313",
  Transform: "\ue25e",
  Stop: "\ue047",
  Forward: "\ue5df",
  Back: "\ue5de",
  Pointer: "\uebb9",
  Scissor: "\ue14e",
  Shift: "\uea18",
  Stretch: "\ue40d",
  Snapping: "\ue3b4",
  Chain: "\ue157",
  Eye: "\ue8f4",
  Ear: "\ue023",
  EyeCrossed: "\ue8f5",
  EarCrossed: "\uf104",
};
