import { Color } from './utils/color';
export declare const FALLBACK_THEME: import('./main').Theme;
export declare const DOUBLE_CLICK_INTERVAL = 500;
export declare const RESIZE_LEEWAY = 4;
export declare const H_RESIZE_CURSOR = "ew-resize";
export declare const V_RESIZE_CURSOR = "ns-resize";
export declare const BUTTON_HOVERED_CHANGE = -15;
export declare const SCROLLBAR_WIDTH = 4;
export declare const SCROLLBAR_HOVERED_WIDTH = 9;
export declare const SCROLLBAR_ROUNDING = 999;
export declare const SLIDER_LINE_HEIGHT = 6;
export declare const SLIDER_DOT_RADIUS = 8;
export declare const SLIDER_LINE_ROUNDING = 999;
export declare const SLIDER_DOT_ROUNDING = 999;
export declare const TEXT_HIGHLIGHT: Color;
export declare const TEXTINPUT_CARET_COLOR: Color;
export declare const DRAGINPUT_SCALING = 0.5;
export declare const MENU_MIN_WIDTH = 100;
export declare const TOOLTIP_HOVER_TIME = 500;
export declare const TOOLTIP_CURSOR_OFFSET_X = 0;
export declare const TOOLTIP_CURSOR_OFFSET_Y = 22;
