import { Pos2D } from './utils/shapes/pos2d';
import { Vec2D } from './utils/shapes/vec2d';
export declare class Context {
    private canvas;
    private interactionHolds;
    private _mousePos;
    private _mouseDelta;
    private _isMouseDown;
    private _justPressedMouse;
    private _justReleasedMouse;
    private _justPressedRightMouse;
    private _justDoubleClicked;
    private _scrollDelta;
    private _cursor;
    private _heldKeys;
    private _justPressedKeys;
    private _justReleasedKeys;
    private _isDraggingFile;
    private _droppedFiles;
    private hiddenTextarea;
    constructor(canvas: HTMLCanvasElement);
    pauseInteraction(): void;
    resumeInteraction(): void;
    peekAtRealMousePos(): Pos2D;
    refresh(): void;
    collectTextInput(initialText: string, callback: (updatedText: string, selectionStart: number, selectionEnd: number) => void): void;
    setTextSelectionRange(start: number, end?: number): void;
    get mousePos(): Pos2D;
    get mouseDelta(): Vec2D;
    get isMouseDown(): boolean;
    get justPressedMouse(): boolean;
    get justReleasedMouse(): boolean;
    get justPressedRightMouse(): boolean;
    get justDoubleClicked(): boolean;
    get scrollDelta(): Vec2D;
    get cursor(): string;
    set cursor(cursor: string);
    get heldKeys(): string[];
    get justPressedKeys(): string[];
    get justReleasedKeys(): string[];
    get isDraggingFile(): boolean;
    get droppedFiles(): FileList | null;
}
